print('Введите Ваше имя в нижнем регистре (с маленькой буквы): ')
name = input().title()
print('Введите Вашу фамилию в нижнем регистре (с маленькой буквы): ')
surname = input().title()
print(name + ' ' + surname)
